name: Deploy to Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: |
          npm ci
          npm run build
        env:
          CI: true
        
      - name: Create production build
        run: |
          rm -rf node_modules
          npm ci --production
          mkdir -p dist/node_modules
          cp -r node_modules/* dist/node_modules/
          cd dist
          zip -r ../function.zip .
          cd ..
          zip -g function.zip package.json
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update Lambda configuration
        run: |
          aws lambda update-function-configuration \
            --function-name notion-x-publisher \
            --handler index.handler \
            --runtime nodejs18.x \
            --timeout 300 \
            --memory-size 1024
        
      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name notion-x-publisher \
            --zip-file fileb://function.zip 