name: Deploy to Lambda

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Install production dependencies
        run: |
          rm -rf node_modules
          npm ci --production
        
      - name: Prepare deployment package
        run: |
          mkdir -p dist/node_modules
          cp -r node_modules/* dist/node_modules/
          cd dist
          zip -r ../function.zip .
          cd ..
          zip -g function.zip package.json
          
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
          
      - name: Update Lambda configuration
        run: |
          aws lambda update-function-configuration \
            --function-name notion-x-publisher \
            --handler index.default \
            --runtime nodejs18.x \
            --timeout 300 \
            --memory-size 256
          
      - name: Deploy to AWS Lambda
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ${{ secrets.AWS_REGION }}
          function_name: notion-x-publisher
          zip_file: function.zip 